Make the Body and About of Portfolio
VictorOmarT/Project-1-Mobile pull request #2
Opened 2021-07-09 21:50 UTC by VictorOmarT

2021-07-09 23:05 UTC, voscarmv requested changes
Hi @VictorOmarT , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- Please check out my comments on best HTML/CSS practices.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a screenshot to your Readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 23:05 UTC, voscarmv commented on index.html
> +        </section>
- [ ] Please mind proper HTML indentation and delete unnecessary blank lines in your whole document to keep with the best HTML practices. Use 2-space indentation and only use blank lines to separate significant sections of code.

2021-07-09 23:05 UTC, voscarmv commented on main.css
> +  margin-left: 20px;
- [ ] Please keep your code DRY by creating a class for redundant CSS attributes. In this case, `margin-left: 20px` appears 6 times. You may use this tool to check for CSS redundancy in the future: https://courses.cs.washington.edu/courses/cse154/20su/resources/assets/css-redundancy-checker/index.html
![image](https://user-images.githubusercontent.com/2739245/125143344-09fffe80-e0e0-11eb-8a5c-7e68ca6923b1.png)

2021-07-10 00:25 UTC, voscarmv requested changes
Hi @VictorOmarT , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- I noticed you marked most of my requested changes as complete, but did not really apply them. Let's please go back and try to complete all the mandatory requirements for this challenge!

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a screenshot to your README file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-10 00:25 UTC, voscarmv commented on index.html
> +            </div>
- [ ] We are still not using proper `<ul>` and `<li>` elements to list the technologies here. Please fix this by using the proper list tags in this and the other projects.

2021-07-10 00:25 UTC, voscarmv commented on index.html
> +        </div>
- [ ] This project is still missing a `View Project` `<a>` link or `<burron>`. It's also missing a proper `<ul>` `<li>` list of technologies. Please fix it.

2021-07-10 00:25 UTC, voscarmv commented on index.html
> +    </section>
- [ ] As mentioned earlier, please use proper `2-space indentation` for your HTML. You may change this value in your Visual Studio Code settings. Check out this youtube video on how to do this: https://www.youtube.com/watch?v=m6gUdoRIRz8

2021-07-10 02:06 UTC, od-c0d3r approved these changes
Hi @VictorOmarT , 

# Approved 🥳 

Good Job implementing the previous reviewer required changes 👏🏼 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional Changes 

- [ ] It would be awesome if you would Implement the `View Project` link that was required by the previous reviewer -_and you nicely added it to the end of your page_- to each `See project` button you have with an effect of your choice like `hover` 👍🏼 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-13 19:11 UTC, merged