Portfolio:  Desktop Version
VictorOmarT/Project-1-Mobile pull request #5
Opened 2021-07-16 17:09 UTC by VictorOmarT

Task completed in this PR:

- Make the Desktop version of the project
- Learn about @Media Queries
- Mobile-first design

2021-07-16 18:04 UTC, Shaher-11 requested changes
#### Hello @VictorOmarT,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Check the comments below:point_down:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
>          <h3>I’am a Software Developer</h3>
The text is overlapping here 
### Original design
![right](https://user-images.githubusercontent.com/58376020/125988591-1c066ab9-56bf-478b-a731-0751614bcbe8.png)

### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125988616-a339e28d-f38a-4959-a827-8cff258334ef.png)

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
> +          <div>
the section needs to be centered as shown below 
### Original design
![right](https://user-images.githubusercontent.com/58376020/125988845-1f7f84f3-aa4e-4044-a087-01f17c1d35c3.png)
### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125988858-39dfcb53-8a61-4ba5-99a8-4797caa395ed.png)

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
> +          </p>
The projects should be centered in columns as shown below
### Original design
![right](https://user-images.githubusercontent.com/58376020/125989169-c0900528-1ec8-4055-b4ae-4a0f47a100a6.png)

### Your project
![wrong](https://user-images.githubusercontent.com/58376020/125989200-c1e6fc74-41b3-482d-9ff8-37ccf597fad6.png)

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
> +        <button class="butm en">Get My Resume</button>
Add some space between the button and the paragraph 
### Original design
![right](https://user-images.githubusercontent.com/58376020/125989432-05a22ca9-50dc-48ae-86ab-c79c91d02cfb.png)

### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125989459-c35f6fa9-f766-47e2-adc7-7fbacbfaa1fd.png)

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
>        </div>
the section needs to be styled based on the given design below
### Original design
![right](https://user-images.githubusercontent.com/58376020/125989710-9580019b-3c64-4a17-9000-927292d18172.png)

### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125989740-f030bd42-7561-41b6-9dfe-ec9be0bf893c.png)

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
>        </form>
Reduce the width of the form and style the text as shown below
### Original Design
![right](https://user-images.githubusercontent.com/58376020/125990083-80d0b014-730f-4810-afaf-eb251ae66641.png)

### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125990120-fd391552-098a-458a-a3ed-fc4c9cf67763.png)

2021-07-16 18:04 UTC, Shaher-11 commented on index.html
>        </form>
Add the social links below the form
![right](https://user-images.githubusercontent.com/58376020/125990208-c27c6b1a-bdc1-48b9-94aa-e0def1a9a19d.png)

2021-07-17 00:16 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️ 


## Hello @VictorOmarT ✋🏼  Nice done with working on last review.However there are still some issues you should fix. Please fix them then your project will be approved.





### ♻️ Request changes ♻️
 

- [ ] _**Check the comment about that  under the review.**_

### OPTIONAL SUGGESTIONS

#### These are optional but highly recommended.

- [ ] _**Check the comment about that  under the review.**_

- [ ] Your commit messages should always start  with capital letters and you should write an imperative tense. I see some of them are not like that. You can change them by using `git rebase`. Please watch this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) and check this [article](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
- [ ]  Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start). 



### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)



___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-17 00:16 UTC, ahmetbozaci commented on index.html
> +              </button>
**Requirement**
- [x] Button position is not like in original design please fix it.
- [x] Also you can add placeholder in form box.

**Original:**
![image](https://user-images.githubusercontent.com/38635158/126018292-516bce54-9be8-4ffe-82cf-d063e6c4ae64.png)

___
**Your design:**
![image](https://user-images.githubusercontent.com/38635158/126018312-6f8e8b90-124c-466e-8883-14b1d1129561.png)

2021-07-17 00:16 UTC, ahmetbozaci commented on index.html
> +        <button class="butm en">Get My Resume</button>
Nice to fix last review.

### OPTIONAL
- [ ] Button  is not same like original. Also you can add button styling. Active,Hover,Pressed.

2021-07-17 00:16 UTC, ahmetbozaci commented on index.html
> +        <img src="pictures/Enabled.png" class="only-mob" alt="menu" />
### OPTIONAL
- [ ] Hamburger icon should appear only in mobile version. You can fix it.
- [ ]  when ı change screen width ı ı can scroll it horizontally. You can fix it too. Page should fit when you change screen width.
![image](https://user-images.githubusercontent.com/38635158/126018974-f57db43b-d34c-41fe-8017-d622de8de7f4.png)

2021-07-17 00:16 UTC, ahmetbozaci commented on index.html
> +      </div>
### Optional
- [ ] I can't see project images. They are in there but not showing. Something wrong in your folder path. I am sure it is working  your side. But it is has to work every pc.  You can check with this [website](https://raw.githack.com)

![image](https://user-images.githubusercontent.com/38635158/126019195-2891fdf3-1ae6-4e73-b0c2-07751ccf5460.png)

2021-07-17 01:07 UTC, VictorOmarT commented on index.html
> +              </button>
I don't know why but the form box always has blank spaces and looks like it doesn't have a placeholder but it does. :)

2021-07-17 02:32 UTC, voscarmv approved these changes
Hi @VictorOmarT , 

I've decided to approve this project because, officially, you have completed all the mandatory changes requested by @ahmetbozaci . Also, I've decided to save you the trouble of repeating the week, as most of the page seems fairly complete.

## HOWEVER ❗ 

There are just **too many** unmet optional changes in this project! And some of them are in fact mandatory according to the project requirements. Please take a step back and fix all the optional changes.

I will make an exception this time, but it is **extremely important** that you fix these issues even after I've approved this project. The next Code Reviewer might not be as understanding as me and could ask you to repeat the week if they see that you have not met the necessary requirements.

Take this as a friendly warning!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-17 14:40 UTC, ahmetbozaci commented on index.html
> +              </button>
- In design from box color is not visible so better adding placeholder.
- Also your brach names are not meaningful. You should write more descriptive name to your next projects.
[how to change branch name](https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/)

2021-07-18 19:00 UTC, merged